import type { Database, Project, Task } from "./model";

const today = new Date();
const day = (offset: number) =>
  new Date(today.getTime() + offset * 86400000).toISOString().slice(0, 10);
const stamp = new Date().toISOString();
const projects: Project[] = [
  {
    id: "aky-mayo",
    workspaceId: "symco",
    kind: "symco",
    name: "Maionese Popular + Premium",
    description:
      "Desenvolvimento de duas formulações de maionese com foco em sabor, estabilidade, viabilidade industrial e posicionamento de mercado.",
    clientId: "aky",
    ownerId: "mariana",
    memberIds: ["mariana", "rafael", "carlos"],
    methodologyId: "symco-food",
    moduleIds: ["product", "quality", "insights"],
    status: "active",
    health: "on_track",
    currentStageId: "develop",
    startDate: day(-38),
    dueDate: day(45),
    favorite: true,
    tags: ["innovation"],
    createdAt: stamp,
  },
  {
    id: "puddings",
    workspaceId: "symco",
    kind: "symco",
    name: "Linha de Pudins",
    description:
      "Nova linha de sobremesas com formulação e embalagem prontas para escala.",
    clientId: "aky",
    ownerId: "rafael",
    memberIds: ["rafael", "mariana"],
    methodologyId: "symco-food",
    moduleIds: ["product", "supply"],
    status: "active",
    health: "attention",
    currentStageId: "quality",
    startDate: day(-66),
    dueDate: day(24),
    favorite: true,
    tags: [],
    createdAt: stamp,
  },
  {
    id: "snack",
    workspaceId: "symco",
    kind: "symco",
    name: "Snack Proteico",
    description:
      "Produto de alto teor proteico para novos canais de distribuição.",
    clientId: "nova",
    ownerId: "carlos",
    memberIds: ["carlos", "mariana"],
    methodologyId: "symco-food",
    moduleIds: ["product", "insights"],
    status: "active",
    health: "at_risk",
    currentStageId: "define",
    startDate: day(-16),
    dueDate: day(72),
    tags: [],
    createdAt: stamp,
  },
  {
    id: "personal",
    workspaceId: "personal",
    kind: "independent",
    name: "Nova Categoria",
    description: "Planejamento de um novo negócio independente.",
    ownerId: "mariana",
    memberIds: ["mariana"],
    methodologyId: "simple",
    moduleIds: [],
    status: "planning",
    health: "on_track",
    currentStageId: "plan",
    startDate: day(-2),
    dueDate: day(110),
    tags: [],
    createdAt: stamp,
  },
];
const demo = (
  id: string,
  projectId: string,
  title: string,
  stageId: string,
  status: Task["status"],
  offset: number,
  assigneeId: string,
): Task => ({
  id,
  projectId,
  title,
  stageId,
  status,
  assigneeId,
  priority: offset < 7 ? "high" : "medium",
  dueDate: day(offset),
  dependencyIds: [],
  createdAt: stamp,
});

export function createSeed(): Database {
  return {
    version: 1,
    users: [
      { id: "mariana", name: "Mariana Costa", email: "mariana@symco.example" },
      { id: "rafael", name: "Rafael Lima", email: "rafael@symco.example" },
      { id: "carlos", name: "Carlos Eduardo", email: "carlos@symco.example" },
    ],
    workspaces: [
      {
        id: "symco",
        name: "Symco Food Tech",
        memberIds: ["mariana", "rafael", "carlos"],
        moduleIds: [
          "insights",
          "product",
          "quality",
          "academy",
          "supply",
          "gomarket",
        ],
      },
      {
        id: "personal",
        name: "Projetos pessoais",
        memberIds: ["mariana"],
        moduleIds: [],
      },
    ],
    organizations: [
      { id: "symco-org", workspaceId: "symco", name: "Symco Food Tech" },
    ],
    clients: [
      {
        id: "aky",
        workspaceId: "symco",
        name: "Aky Alimentos",
        contact: "contato@aky.example",
        status: "active",
      },
      {
        id: "nova",
        workspaceId: "symco",
        name: "Nova Alimentos",
        status: "active",
      },
    ],
    projects,
    members: projects.flatMap((project) =>
      project.memberIds.map((userId) => ({
        projectId: project.id,
        userId,
        role:
          userId === project.ownerId
            ? ("project_manager" as const)
            : ("member" as const),
      })),
    ),
    methodologies: [
      {
        id: "symco-food",
        workspaceId: "symco",
        name: "Metodologia Symco Food",
        stages: [
          "Descobrir",
          "Definir",
          "Desenvolver",
          "Regulatório",
          "Qualidade",
          "Aprovar",
          "Escalar",
        ].map((name, order) => ({
          id: [
            "discover",
            "define",
            "develop",
            "regulatory",
            "quality",
            "approve",
            "scale",
          ][order],
          name,
          order,
        })),
      },
      {
        id: "simple",
        workspaceId: "personal",
        name: "Projeto simples",
        stages: ["Planejar", "Executar", "Revisar"].map((name, order) => ({
          id: ["plan", "execute", "review"][order],
          name,
          order,
        })),
      },
    ],
    gates: [
      {
        id: "gate-aky",
        projectId: "aky-mayo",
        stageId: "develop",
        title: "Aprovação da formulação piloto",
        status: "pending",
        dueDate: day(18),
        requiredTaskIds: ["task-3"],
        requiredDocumentIds: [],
        approverIds: ["mariana"],
      },
    ],
    tasks: [
      demo(
        "task-1",
        "aky-mayo",
        "Consolidar briefing e requisitos",
        "discover",
        "done",
        -21,
        "mariana",
      ),
      demo(
        "task-2",
        "aky-mayo",
        "Benchmarking de mercado",
        "define",
        "done",
        -12,
        "carlos",
      ),
      demo(
        "task-3",
        "aky-mayo",
        "Formulação piloto",
        "develop",
        "in_progress",
        5,
        "rafael",
      ),
      demo(
        "task-4",
        "aky-mayo",
        "Teste de estabilidade",
        "quality",
        "todo",
        17,
        "mariana",
      ),
      demo(
        "task-5",
        "aky-mayo",
        "Revisão regulatória",
        "regulatory",
        "todo",
        24,
        "carlos",
      ),
      demo(
        "task-6",
        "puddings",
        "Aprovar embalagem",
        "quality",
        "in_progress",
        8,
        "rafael",
      ),
      demo(
        "task-7",
        "puddings",
        "Validar lote piloto",
        "approve",
        "done",
        -5,
        "mariana",
      ),
      demo(
        "task-8",
        "snack",
        "Definir posicionamento",
        "define",
        "blocked",
        3,
        "carlos",
      ),
      demo(
        "task-9",
        "snack",
        "Pesquisa com consumidores",
        "discover",
        "done",
        -4,
        "mariana",
      ),
      demo(
        "task-10",
        "personal",
        "Definir público-alvo",
        "plan",
        "todo",
        25,
        "mariana",
      ),
    ],
    subtasks: [],
    comments: [
      {
        id: "comment-1",
        projectId: "aky-mayo",
        taskId: "task-3",
        authorId: "mariana",
        body: "A primeira rodada de testes ficou pronta. Vamos comparar as duas propostas.",
        createdAt: stamp,
      },
    ],
    qualityRecords: [
      {
        id: "quality-1",
        projectId: "aky-mayo",
        title: "Auditoria de formulação piloto",
        kind: "audit",
        status: "in_progress",
        ownerId: "mariana",
        dueDate: day(8),
        description: "Conferir registros e critérios de liberação.",
      },
      {
        id: "quality-2",
        projectId: "snack",
        title: "Rastreabilidade de ingredientes",
        kind: "nonconformity",
        status: "open",
        ownerId: "carlos",
        dueDate: day(4),
        description: "Validar lote e fornecedor alternativo.",
      },
      {
        id: "quality-3",
        projectId: "aky-mayo",
        title: "Ajustar protocolo sensorial",
        kind: "capa",
        status: "open",
        ownerId: "rafael",
        dueDate: day(12),
        description:
          "Documentar causa, ação corretiva e evidência de conclusão.",
      },
    ],
    automations: [],
    attachments: [
      {
        id: "doc-1",
        projectId: "aky-mayo",
        title: "Briefing técnico",
        type: "DOCX",
        category: "Formulação",
        moduleId: "product",
        version: "1.0",
        status: "draft",
        createdAt: stamp,
        createdBy: "mariana",
      },
      ...[
        {
          id: "doc-2",
          projectId: "aky-mayo",
          title: "Relatório de estabilidade.pdf",
          type: "PDF",
          category: "Qualidade e Regulatório",
          moduleId: "quality",
          status: "review" as const,
        },
        {
          id: "doc-3",
          projectId: "aky-mayo",
          title: "Benchmarking maioneses.xlsx",
          type: "XLSX",
          category: "Estudos e Pesquisas",
          moduleId: "insights",
          status: "draft" as const,
        },
        {
          id: "doc-4",
          projectId: "puddings",
          title: "Especificação técnica.docx",
          type: "DOCX",
          category: "Formulação",
          moduleId: "product",
          status: "approved" as const,
        },
        {
          id: "doc-5",
          projectId: "snack",
          title: "Plano de auditoria.pptx",
          type: "PPTX",
          category: "Qualidade e Regulatório",
          moduleId: "quality",
          status: "draft" as const,
        },
        {
          id: "doc-6",
          projectId: "aky-mayo",
          title: "Estudo sensorial.docx",
          type: "DOCX",
          category: "Estudos e Pesquisas",
          moduleId: "insights",
          status: "draft" as const,
        },
        {
          id: "doc-7",
          projectId: "puddings",
          title: "Plano de lançamento.pptx",
          type: "PPTX",
          category: "Marketing e Mercado",
          moduleId: "gomarket",
          status: "draft" as const,
        },
        {
          id: "doc-8",
          projectId: "snack",
          title: "Custo industrial.xlsx",
          type: "XLSX",
          category: "Produção e Escala",
          moduleId: "supply",
          status: "draft" as const,
        },
      ].map((doc) => ({
        ...doc,
        createdAt: stamp,
        createdBy: "mariana",
        version: "1.0",
      })),
    ],
    approvals: [
      {
        id: "approval-1",
        projectId: "aky-mayo",
        title: "Formulação piloto",
        requestedBy: "rafael",
        approverIds: ["mariana"],
        status: "pending",
        dueDate: day(14),
        createdAt: stamp,
      },
    ],
    decisions: [
      {
        id: "decision-1",
        projectId: "aky-mayo",
        stageId: "define",
        title: "Duas versões de formulação",
        description:
          "Manter opções popular e premium para validação sensorial.",
        decidedBy: "mariana",
        decidedAt: stamp,
        attachmentIds: [],
      },
    ],
    risks: [
      {
        id: "risk-1",
        projectId: "snack",
        title: "Atraso no fornecedor de ingredientes",
        description: "A amostra ainda não foi liberada.",
        probability: "high",
        impact: "high",
        ownerId: "carlos",
        status: "open",
        mitigation: "Homologar fornecedor alternativo.",
      },
    ],
    milestones: [
      {
        id: "milestone-1",
        projectId: "aky-mayo",
        title: "Validação sensorial",
        dueDate: day(12),
        status: "pending",
      },
      {
        id: "milestone-2",
        projectId: "puddings",
        title: "Embalagem aprovada",
        dueDate: day(8),
        status: "pending",
      },
    ],
    activities: [
      {
        id: "activity-1",
        workspaceId: "symco",
        projectId: "aky-mayo",
        actorId: "mariana",
        type: "comment_added",
        entityId: "comment-1",
        summary: "comentou na formulação piloto",
        createdAt: stamp,
      },
    ],
    notifications: [],
    tags: [
      {
        id: "innovation",
        workspaceId: "symco",
        name: "Inovação",
        color: "#18a7d0",
      },
    ],
  };
}
