import { ChevronRight, FileText, LayoutList, Search, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { gates } from '../data'
import { statuses } from '../config/navigation'
import type { Task, TaskStatus } from '../types'
import { Progress, StatusBadge } from '../components/ui'

export function BoardPage({ tasks, select }: { tasks: Task[]; select: (task: Task) => void }) {
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState<TaskStatus | 'Todos'>('Todos')
  const filtered = useMemo(() => tasks.filter(task => (filter === 'Todos' || task.status === filter) && `${task.id} ${task.title} ${task.owner} ${task.gate}`.toLowerCase().includes(query.toLowerCase())), [tasks, query, filter])
  return <div className="page-stack board-page">
    <section className="toolbar card"><label><Search size={17} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar atividade, ID ou responsável" /></label><div className="filter-chips"><button className={filter === 'Todos' ? 'active' : ''} onClick={() => setFilter('Todos')}>Todas</button>{statuses.slice(0, 4).map(status => <button key={status} className={filter === status ? 'active' : ''} onClick={() => setFilter(status)}>{status}</button>)}</div><span className="result-count"><LayoutList size={15} /> {filtered.length} itens</span></section>
    <div className="gate-groups">{gates.map(gate => { const items = filtered.filter(task => task.gate.includes(gate[0])); if (!items.length) return null; return <section className="task-group" key={gate[0]}><div className="task-group-title"><span>{gate[0]}</span><div><h2>{gate[1]}</h2><small>{gate[3]}</small></div><strong>{items.length}</strong></div><div className="task-list">{items.map(task => <button className="task-row" key={task.id} onClick={() => select(task)}><span className={`priority-mark priority-${task.priority.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '')}`} /><div className="task-identity"><small>{task.id} · {task.module}</small><strong>{task.title}</strong><span>{task.owner}</span></div><div className="task-evidence"><small>EVIDÊNCIA</small><span>{task.evidence}</span></div><StatusBadge status={task.status} /><div className="task-progress"><span>{task.progress}%</span><Progress value={task.progress} /></div><time>{task.due.slice(0, 5)}</time><ChevronRight size={17} /></button>)}</div></section> })}</div>
  </div>
}

export function TaskDrawer({ task, close, save }: { task: Task; close: () => void; save: (task: Task) => void }) {
  const [draft, setDraft] = useState(task)
  return <div className="overlay" onMouseDown={event => event.target === event.currentTarget && close()}><section className="drawer" role="dialog" aria-modal="true" aria-labelledby="task-title"><div className="drawer-head"><div><span className="eyebrow">{task.id} · {task.gate}</span><h2 id="task-title">{task.title}</h2></div><button className="icon-button" onClick={close} aria-label="Fechar"><X size={20} /></button></div><div className="drawer-body"><div className="field-grid"><label>Status<select value={draft.status} onChange={event => setDraft({ ...draft, status: event.target.value as TaskStatus, progress: event.target.value === 'Concluído' ? 100 : draft.progress })}>{statuses.map(status => <option key={status}>{status}</option>)}</select></label><label>Prioridade<select value={draft.priority} onChange={event => setDraft({ ...draft, priority: event.target.value as Task['priority'] })}><option>Crítica</option><option>Alta</option><option>Média</option></select></label></div><label className="range-field"><span>Progresso <b>{draft.progress}%</b></span><input type="range" min="0" max="100" step="5" value={draft.progress} onChange={event => { const progress = Number(event.target.value); setDraft({ ...draft, progress, status: progress === 100 ? 'Concluído' : progress > 0 ? 'Em andamento' : draft.status }) }} /></label><div className="detail-list"><div><span>Responsável</span><strong>{task.owner}</strong></div><div><span>Apoio</span><strong>{task.support}</strong></div><div><span>Período</span><strong>{task.start} — {task.due}</strong></div><div><span>Dependência</span><strong>{task.dependency || 'Sem dependência'}</strong></div><div><span>Evidência</span><strong>{task.evidence}</strong></div><div><span>Próxima ação</span><strong>{task.nextAction}</strong></div></div><div className="inline-info"><FileText size={18} /><span>Vincule a evidência no módulo Documentos para preservar a trilha de decisão.</span></div></div><div className="drawer-foot"><button className="button subtle" onClick={close}>Cancelar</button><button className="button primary" onClick={() => save(draft)}>Salvar atividade</button></div></section></div>
}
