import { Check, FileCheck2, FileText, ShieldCheck } from 'lucide-react'
import { documents, gates } from '../data'
import { Progress, StatusBadge } from '../components/ui'

export function DocumentsPage({ done, setDone }: { done: string[]; setDone: (documents: string[]) => void }) {
  const toggle = (name: string) => setDone(done.includes(name) ? done.filter(document => document !== name) : [...done, name])
  const coverage = Math.round(done.length / documents.length * 100)
  return <div className="page-stack documents-page"><section className="document-overview"><div><strong>{coverage}%</strong><Progress value={coverage} tone="violet" /><small>{done.length} de {documents.length} evidências aprovadas</small></div><div><ShieldCheck size={24} /><span><strong>Regra de liberação</strong>Um Gate só avança quando sua evidência obrigatória estiver disponível e aprovada.</span></div></section><div className="document-groups">{gates.map(gate => { const items = documents.filter(document => document[1] === gate[0]); if (!items.length) return null; return <section key={gate[0]}><header><span>{gate[0]}</span><div><h2>{gate[1]}</h2><small>{gate[3]}</small></div><strong>{items.filter(item => done.includes(item[0])).length}/{items.length}</strong></header><div>{items.map(document => { const ready = done.includes(document[0]); return <article className={ready ? 'document-ready' : ''} key={document[0]}><span className="file-icon">{ready ? <FileCheck2 size={20} /> : <FileText size={20} />}</span><div><h3>{document[0]}</h3><small>Responsável · {document[2]}</small></div><StatusBadge status={ready ? 'Aprovado' : 'Aguardando informação'} /><button className={`button ${ready ? 'subtle' : 'primary'}`} onClick={() => toggle(document[0])}>{ready ? <><Check size={15} />Aprovado</> : 'Simular envio'}</button></article> })}</div></section> })}</div></div>
}
