import { ArrowRight, CalendarClock, CheckCircle2, MessageSquareText, Users } from 'lucide-react'

const roles = [['01', 'Preparar', 'Project Lead / PMO'], ['02', 'Recomendar', 'P&D + especialistas'], ['03', 'Aprovar', 'Aky Alimentos'], ['04', 'Registrar', 'Project Lead / PMO']]
const raci = [['Brief / targets', 'A/R', 'C', 'C', 'C', 'A/C'], ['Desenvolver fórmula', 'C', 'A/R', 'C', 'C', 'I'], ['Verificação regulatória', 'I', 'C', 'A/R', 'I', 'I'], ['Condições de fabricação', 'C', 'C', 'C', 'A/R', 'R'], ['Aprovar produto', 'C', 'C', 'C', 'C', 'A/R'], ['Teste industrial', 'A', 'R', 'C', 'R', 'R'], ['Lançamento', 'I', 'I', 'I', 'I', 'A/R']]

export function GovernancePage() {
  return <div className="page-stack governance-page"><section className="decision-flow">{roles.map((role, index) => <div key={role[0]}><span>{role[0]}</span><small>{role[1]}</small><strong>{role[2]}</strong>{index < roles.length - 1 && <ArrowRight size={18} />}</div>)}</section><section className="governance-layout"><div className="card raci-card"><header><div><span className="eyebrow">RESPONSABILIDADES</span><h2>Matriz RACI</h2></div><div className="raci-legend"><span><b>R</b> Executa</span><span><b>A</b> Aprova</span><span><b>C</b> Consultado</span><span><b>I</b> Informado</span></div></header><div className="table-scroll"><table className="raci"><thead><tr><th>Decisão / atividade</th><th>PL / PMO</th><th>P&D</th><th>Reg.</th><th>Qualidade</th><th>Aky</th></tr></thead><tbody>{raci.map(row => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`} className={index ? 'mono' : ''}>{cell}</td>)}</tr>)}</tbody></table></div></div><aside className="rituals"><Ritual icon={CalendarClock} title="Weekly Project Sync" cadence="Semanal · 30–45 min" output="Board atualizado + ações" /><Ritual icon={MessageSquareText} title="Technical Sync" cadence="Sob demanda · 30–60 min" output="Decisões técnicas registradas" /><Ritual icon={CheckCircle2} title="Gate Review" cadence="Por marco · 30–45 min" output="Go / Hold / Return" /><Ritual icon={Users} title="Client Steering" cadence="Quinzenal · 30 min" output="Prioridades e decisões" /></aside></section></div>
}

function Ritual({ icon: Icon, title, cadence, output }: { icon: typeof Users; title: string; cadence: string; output: string }) {
  return <article className="card ritual"><span><Icon size={18} /></span><div><h3>{title}</h3><p>{cadence}</p><small>SAÍDA</small><strong>{output}</strong></div></article>
}
